/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type AgeRange int
type LocationType int

const (
	AgeRangeAll AgeRange = iota + 1
	AgeRangeBt18n24
	AgeRangeBt25n40
	AgeRangeMore40

	LocationWorld LocationType = iota + 1
	LocationCountry
	LocationNearby
)

type DisplaySettings struct {
	UserID         int          `json:"userId,omitempty"`
	ShowMeAges     AgeRange     `json:"showMeAges,omitempty"`
	HideMeFromAges AgeRange     `json:"hideMeFromAges,omitempty"`
	ShowThemesID   []int        `json:"showThemesId,omitempty"`
	HideThemesID   []int        `json:"hideThemesId,omitempty"`
	Location       LocationType `json:"location,omitempty"`
}
