/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type DisplaySettings struct {
	UserId         int    `json:"userId,omitempty"`
	ShowMeAges     string `json:"showMeAges,omitempty"`
	HideMeFromAges string `json:"hideMeFromAges,omitempty"`
	ShowThemesID   []int  `json:"showThemesId,omitempty"`
	HideThemesID   []int  `json:"hideThemesId,omitempty"`
	Location       string `json:"location,omitempty"`
}
