/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserRegLoginData struct {

	Email string `json:"email,omitempty"`

	// Password in MD5 hash
	Password string `json:"password,omitempty"`
}
