/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserAuthInfo struct {

	UserId int32 `json:"userId,omitempty"`

	AccessKey string `json:"accessKey,omitempty"`
}
