/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

import "time"

type Profile struct {
	UserID int `json:"userId,omitempty"`

	Name string `json:"name,omitempty"`
	// image data in base64
	Avatar string `json:"avatar,omitempty"`

	Birthday time.Time `json:"birthday,omitempty"`

	Interests []int64 `json:"interests,omitempty"`

	LastVisit time.Time

	Country string
}
