/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"rosberry/api"
	"rosberry/middleware"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = middleware.Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}


var routes = Routes{
	Route{
		"GetUserProfile",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/profile/{userId}",
		api.GetUserProfile,
	},

	Route{
		"ShowProfiles",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/profile/showList",
		api.ShowProfiles,
	},

	Route{
		"UpdateUserProfile",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/profile/update",
		api.UpdateUserProfile,
	},

	Route{
		"ThemesList",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/themes",
		api.ThemesList,
	},

	Route{
		"GetDisplaySettings",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/user/settings/{userId}",
		api.GetDisplaySettings,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/login",
		api.LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/logout",
		api.LogoutUser,
	},

	Route{
		"RegistrationUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/registration",
		api.RegistrationUser,
	},

	Route{
		"SetDisplaySettings",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/settings/set",
		api.SetDisplaySettings,
	},
}
