/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"net/http"
	"rosberry/api"
	"rosberry/middleware"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
	AuthNeed    bool
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		handler := route.HandlerFunc
		var logHandler http.Handler

		if route.AuthNeed {
			authHandler := middleware.Auth(handler) //!Не все методы требуют аутентификацию по ключу
			logHandler = middleware.Logger(authHandler, route.Name)
		} else {
			logHandler = middleware.Logger(handler, route.Name)
		}

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(logHandler)
	}

	return router
}

var routes = Routes{
	Route{
		"RegistrationUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/registration",
		api.RegistrationUser,
		false,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/login",
		api.LoginUser,
		false,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/logout",
		api.LogoutUser,
		true,
	},

	Route{
		"GetUserProfile",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/profile/get/{userId}",
		api.GetUserProfile,
		true,
	},

	Route{
		"ShowProfiles",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/profile/getList",
		api.ShowProfiles,
		true,
	},

	Route{
		"UpdateUserProfile",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/profile/update",
		api.UpdateUserProfile,
		true,
	},

	Route{
		"ThemesList",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/themes",
		api.ThemesList,
		true,
	},

	Route{
		"GetDisplaySettings",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/user/settings/{userId}",
		api.GetDisplaySettings,
		true,
	},

	Route{
		"SetDisplaySettings",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/settings/set",
		api.SetDisplaySettings,
		true,
	},
}
