/*
 * Rosberry Mobile APP API (Test work)
 *
 * Test work for rosberry
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/Sm1Le55/Rosberry/0.0.1/",
		Index,
	},

	Route{
		"GetUserProfile",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/profile/{userId}",
		GetUserProfile,
	},

	Route{
		"ShowProfiles",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/profile/showList",
		ShowProfiles,
	},

	Route{
		"UpdateUserProfile",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/profile/update",
		UpdateUserProfile,
	},

	Route{
		"ThemesList",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/themes",
		ThemesList,
	},

	Route{
		"GetDisplaySettings",
		strings.ToUpper("Get"),
		"/Sm1Le55/Rosberry/0.0.1/user/settings/{userId}",
		GetDisplaySettings,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/logout",
		LogoutUser,
	},

	Route{
		"RegistrationUser",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/registration",
		RegistrationUser,
	},

	Route{
		"SetDisplaySettings",
		strings.ToUpper("Post"),
		"/Sm1Le55/Rosberry/0.0.1/user/settings/set",
		SetDisplaySettings,
	},
}
